### ISSUE TITLE
Community Slack/Gitter Server

### ISSUE THREAD

**Issue by iKevinY** [ubcfoss/awesome-ubc-foss#5]
Not strictly an issue related to this repository itself, but would there be any interest in a community Slack or [Gitter](https://gitter.im) server to coordinate working on @ubcfoss projects / general discussion about software development within the UBC community? (Or if one already exists, adding a README badge linking to it would be helpful!)

**Edit**: I've created [**ubcfoss.slack.com**](https://ubcfoss.slack.com) to see if a Slack channel will gain any traction. Comment in this issue if your UBC email subdomain isn't listed!

**Comment by dohliam** [comment]
That's a great idea! :+1: If you set something like this up we can definitely link to it from the readme.

**Comment by darshandsoni** [comment]
I second that. We haven't made anything yet @iKevinY so you could go ahead and create something.
Not sure which platform would serve the purposes best (enter the eternal issues with messaging platforms) but we can do with one. 

I have to say that several engineering slack teams I've created have ended up dying down for some reason. This may be due to people having too many slack teams going on / not wanting to use it in the first place. Gitter is less familiar to a lot of users, but ties into the github organisation much better. 

Feel free to create anything though! Submit a PR to link it in the readme :)

**Comment by iKevinY** [comment]
> Not sure which platform would serve the purposes best (enter the eternal issues with messaging platforms) but we can do with one. […] Gitter is less familiar to a lot of users, but ties into the github organisation much better.

Yeah, I'm conflicted about whether Slack or Gitter is the better option.

For the time being, I've gone ahead and created a Slack team at [**ubcfoss.slack.com**](https://ubcfoss.slack.com). Signups are currently open to anyone with an `alumni.ubc.ca` email address; hopefully forcing people to sign up with their UBC email addresses will cut down on the amount of moderation effort required. Maybe we can discuss further over on Slack. 😄

> I have to say that several engineering slack teams I've created have ended up dying down for some reason. This may be due to people having too many slack teams going on / not wanting to use it in the first place.

I feel like the only way to get around this is to achieve some sort of 'critical mass' of users such that there's constantly discussion going on. I suppose there's nothing inherently bad about a Slack team dying down, as it just signifies it wasn't that necessary in the first place.

**Comment by darshandsoni** [comment]
That sounds great @iKevinY! I'll jump on there shortly. 

A small suggestion would be to use `ubc.ca` instead of `alumni.ubc.ca` as a filter. Some members here are not students, but staff. This means they have a `ubc.ca` email address. Additionally, there are people who use faculty / departmental emails such as `sauder.ubc.ca` or `apsc.ubc.ca` too. Not to mention alumni who left before the introduction of `alumni.ubc.ca`.

Apart from that, achieving critical mass might be the solution! Create it and feel free to add sign-up instructions on our readme page :smile:

**Comment by iKevinY** [comment]
@darshandsoni It seems like Slack's account creation page limits domains to a dropdown, so allowing `ubc.ca` doesn't necessarily allow subdomains underneath it. I've manually added in the ones you've listed and we can always add more as we go (or just let people request invitations via [slackin](https://github.com/rauchg/slackin)).

**Comment by dohliam** [comment]
@iKevinY Looks great -- thanks for this!
